apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: 571600847532.dkr.ecr.us-east-1.amazonaws.com/myrepo:latest  # Change this dynamically in CI/CD
        ports:
        - containerPort: 5000
        env:
        - name: PORT
          value: "5000"
        - name: FLASK_DEBUG
          value: "false"  # Set to "true" for debugging if needed
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "250m"
            memory: "256Mi"
        livenessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 3
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 3
          periodSeconds: 5
      restartPolicy: Always


