name: Build and Push to AWS ECR

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 571600847532.dkr.ecr.us-east-1.amazonaws.com

      - name: Set IMAGE_TAG
        run: echo "IMAGE_TAG=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          docker build -t myapp:${{ env.IMAGE_TAG }} .

      - name: Tag Docker image
        run: |
          ECR_REPO_URI=571600847532.dkr.ecr.us-east-1.amazonaws.com/myrepo
          docker tag myapp:${{ env.IMAGE_TAG }} $ECR_REPO_URI:${{ env.IMAGE_TAG }}

      - name: Push Docker image to Amazon ECR
        run: |
          ECR_REPO_URI=571600847532.dkr.ecr.us-east-1.amazonaws.com/myrepo
          docker push $ECR_REPO_URI:${{ env.IMAGE_TAG }}

      - name: Verify pushed image
        run: |
          echo "Pushed image: 571600847532.dkr.ecr.us-east-1.amazonaws.com/myrepo:${{ env.IMAGE_TAG }}"
