name: Multi-Cloud Deployment

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up Docker Build
        run: |
          docker build -t myapp:latest .
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker tag myapp:latest <CLOUD_REGISTRY_URL>/myapp:latest
          docker push <CLOUD_REGISTRY_URL>/myapp:latest

      - name: Configure Kubernetes and Deploy
        run: |
          echo "${{ secrets.KUBE_CONFIG }}" | base64 --decode > kubeconfig.yaml
          export KUBECONFIG=kubeconfig.yaml
          kubectl apply -f deployment.yaml
          kubectl apply -f service.yaml
