name: Build and Push to AWS ECR

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Define AWS Region and ECR Repository
        run: |
          echo "AWS_REGION=us-east-1" >> $GITHUB_ENV
          echo "ECR_REPO_URI=571600847532.dkr.ecr.us-east-1.amazonaws.com/myrepo" >> $GITHUB_ENV

      - name: Login to Amazon ECR
        run: |
          set -e
          aws ecr get-login-password --region ${{ env.AWS_REGION }} | docker login --username AWS --password-stdin ${{ env.ECR_REPO_URI }}

      - name: Set IMAGE_TAG
        run: |
          echo "IMAGE_TAG=$(echo $GITHUB_REF_NAME)-$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          set -e
          docker build --no-cache -t myapp:${{ env.IMAGE_TAG }} .

      - name: Tag Docker image
        run: |
          set -e
          docker tag myapp:${{ env.IMAGE_TAG }} ${{ env.ECR_REPO_URI }}:${{ env.IMAGE_TAG }}

      - name: Push Docker image to Amazon ECR
        run: |
          set -e
          docker push ${{ env.ECR_REPO_URI }}:${{ env.IMAGE_TAG }}

      - name: Verify pushed image
        run: |
          echo "✅ Pushed image: ${{ env.ECR_REPO_URI }}:${{ env.IMAGE_TAG }}"
